name: Build
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - "*.sln"
      - "*.slnx"
      - build/pack.ps1
      - build/pkg.version
      - NuGet.Config
      - src/**
      - test/**
  pull_request_target: # use pull_request_target instead of pull_request to let dependabot have permission to access action secrets.
    branches:
      - main

env:
  DOTNET_NOLOGO: 1
  VERSION: 0.0.1
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
  SOLUTION: InterfaceBaseInvoke.slnx
  IS_PUSH_DEFAULT: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }} -v q

      - name: Test Debug
        run: dotnet test ${{ env.SOLUTION }} --no-restore -c Debug

      - name: Test Release
        run: dotnet test ${{ env.SOLUTION }} --no-restore -c Release

      - name: Test Report
        uses: dorny/test-reporter@main
        if: (success() || failure())
        with:
          name: Test Report
          path: TestResults/**/*.trx
          reporter: dotnet-trx
          list-suites: failed
          list-tests: failed

  build-win:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet x64
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }} -v q

      - name: Test Debug
        run: dotnet test ${{ env.SOLUTION }} --no-restore -c Debug

      - name: Test Release
        run: dotnet test ${{ env.SOLUTION }} --no-restore -c Release

      - name: Test Report
        uses: dorny/test-reporter@main
        if: (success() || failure())
        with:
          name: Test Report
          path: TestResults/**/*.trx
          reporter: dotnet-trx
          list-suites: failed
          list-tests: failed

  publish:
    if: env.IS_PUSH_DEFAULT == 'true'
    runs-on: ubuntu-latest    
    needs: 
      - build
      - build-win
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: NuGet Publish
        
        shell: pwsh
        run: |
          ./build/pack.ps1

      - name: Set variables
        shell: pwsh
        run: |
          $ver = Get-Content -Path ./build/pkg.version
          echo "VERSION=$ver" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo $ver

      - name: Create Tag
        uses: huoshan12345/update-tag@v1
        with:
          tag_name: ${{ env.VERSION }}
          on_tag_exists: skip
          update_if_exists: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
...
